# -*- coding: utf-8 -*-
"""analyse_sentiments.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybJ-a41Y8LQBYGkFHODpuMg4JN9dn5Kc
"""

!pip install pandas numpy scikit-learn matplotlib seaborn transformers spacy nltk textblob
!python -m spacy download fr_core_news_sm

import pandas as pd
import numpy as np
import spacy
import re
from transformers import pipeline
import matplotlib.pyplot as plt
import seaborn as sns
import json
import unittest
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
from collections import Counter, defaultdict

# Téléchargement des ressources NLTK nécessaires
try:
    # NLTK est utilisé ici principalement pour VADER et la segmentation (si spaCy ne l'est pas)
    nltk.download('vader_lexicon', quiet=True)
    nltk.download('punkt', quiet=True)
except:
    pass

# --- 1. Initialisation des Modèles et Ressources NLP ---

# Chargement de spacy pour le traitement en français (Tâche 1.2) [cite: 572]
try:
    nlp = spacy.load("fr_core_news_sm")
except OSError:
    print("Erreur: Le modèle spaCy 'fr_core_news_sm' n'est pas installé. Exécutez : python -m spacy download fr_core_news_sm")
    exit()

# Initialisation des pipelines de Hugging Face pour l'analyse (Tâche 2.1 & 2.3)
# Modèle 1 (Polarité) : Multilingue pour une meilleure robustesse en français
try:
    sentiment_classifier = pipeline(
        "sentiment-analysis",
        model="nlptown/bert-base-multilingual-uncased-sentiment", # Modèle 5 étoiles
        tokenizer="nlptown/bert-base-multilingual-uncased-sentiment"
    )
except Exception as e:
    print(f"Avertissement: Échec du chargement du modèle de sentiment HF. Utilisation des méthodes basées sur lexique. Erreur: {e}")
    sentiment_classifier = None

# Modèle 2 (Émotions) : Utilisation d'un modèle pour détecter les émotions
try:
    emotion_classifier = pipeline(
        "text-classification",
        model="j-hartmann/emotion-english-distilroberta-base",
        return_all_scores=True
    )
except Exception as e:
    print(f"Avertissement: Échec du chargement du modèle d'émotions HF. Utilisation du lexique custom. Erreur: {e}")
    emotion_classifier = None

# VADER (Méthode 2 de polarité) [cite: 569]
sia = SentimentIntensityAnalyzer()

# Dictionnaire d'Aspects (Tâche 1.3 / 2.2)
ASPECTS_DICT = {
    "Produit": ["téléphone", "produit", "qualité", "performance", "rapide", "sonore", "caméra", "autonomie", "application", "mobile"],
    "Prix": ["prix", "coût", "valeur", "élevé", "cher", "abordable", "rapport qualité-prix"],
    "Service": ["service client", "support technique", "support", "client", "impeccable", "lent", "répondre"],
    "Livraison": ["livraison", "rapidité", "express", "emballage", "endommagé", "arrivé"]
}

# Lexique Custom pour la détection d'émotions (Tâche 2.3 - utilisé en fallback ou pour la méthode Custom)
EMOTIONS_LEXIQUE = {
    "Joie / Satisfaction": ["excellent", "parfait", "impeccable", "vivement", "recommande", "satisfait", "exceptionnel"],
    "Colère / Frustration": ["frustré", "furieux", "bug", "lent", "endommagé", "déçu"],
    "Tristesse / Déception": ["déçu", "décevant", "déception", "pas sûr"],
    "Peur / Inquiétude": ["inquiet", "anxieux", "incertain"],
    "Surprise (pos/neg)": ["surprise", "étonnant"],
    "Dégout / Mépris": ["bof", "médiocre", "nul", "horrible"]
}

# Données d'Entrée
avis_clients = [
    "Le téléphone est excellent, très rapide et l’autonomie dure toute la journée. Cependant, la caméra est décevante et le prix trop élevé à mon goût. Service client impeccable!",
    "Livraison rapide mais produit arrivé endommagé. Je suis très frustré et déçu par cette expérience.",
    "Rien à redire! Produit parfait, emballage soigné, livraison express. Je recommande vivement!",
    "La qualité sonore est exceptionnelle mais l’application mobile bug constamment. Support technique lent à répondre.",
    "Bof... produit correct sans plus. Le rapport qualité-prix est moyen. Pas sûr de recommander."
]

# --- 2. Fonctions d'Analyse (Modulaires) ---

def map_hf_score_to_category(score_label):
    """Mappe le label du modèle HF (5 étoiles) à la catégorie requise (5 catégories) [cite: 1048]"""
    if '5' in score_label: return "Très Positif"
    if '4' in score_label: return "Positif"
    if '3' in score_label: return "Neutre"
    if '2' in score_label: return "Négatif"
    if '1' in score_label: return "Très Négatif"
    return "Neutre"

def get_sentiment_score_hf(text):
    """Tâche 2.1 (Méthode 1): Polarité avec modèle HF (score [-1, 1] normalisé)"""
    if sentiment_classifier:
        try:
            result = sentiment_classifier(text)[0]
            star_value = int(result['label'].split()[0])
            score_m1 = (star_value - 3) / 2 # Normalise de 1 à 5 vers -1 à 1
            return score_m1, result['label']
        except Exception:
            return 0.0, "Neutre"
    # Fallback si le modèle HF n'a pas chargé
    return TextBlob(text).sentiment.polarity, "Neutre (Fallback)"

def get_sentiment_score_vader(text):
    """Tâche 2.1 (Méthode 2): Polarité avec VADER (score [-1, 1]) [cite: 569]"""
    return sia.polarity_scores(text)['compound']

def get_sentiment_score_textblob(text):
    """Tâche 2.1 (Méthode 3): Polarité avec TextBlob (score [-1, 1]) [cite: 560]"""
    return TextBlob(text).sentiment.polarity

def analyze_document_sentiment(text):
    """Tâche 1.1 & 2.1: Analyse complète au niveau Document."""
    score_m1, label_m1 = get_sentiment_score_hf(text)
    category = map_hf_score_to_category(label_m1)

    score_m2_vader = get_sentiment_score_vader(text)
    score_m3_textblob = get_sentiment_score_textblob(text) # Utilisé comme M3 pour la comparaison

    # Calcul de la cohérence entre les 3 méthodes [cite: 1072]
    scores = [score_m1, score_m2_vader, score_m3_textblob]
    # La cohérence est inversément proportionnelle à l'écart type des scores
    coherence = 1 - (np.std(scores) / (np.mean(np.abs(scores)) + 0.001))

    return {
        "score_hf": score_m1,
        "category": category,
        "score_vader": score_m2_vader,
        "score_textblob": score_m3_textblob,
        "coherence": coherence
    }

def split_and_analyze_sentences(text):
    """Tâche 1.2: Découpage (avec spaCy) et analyse au niveau phrase."""
    doc = nlp(text)
    sentences = [sent.text.strip() for sent in doc.sents if sent.text.strip()]

    results = []
    category_counts = Counter()

    for sentence in sentences:
        score_m1, label_m1 = get_sentiment_score_hf(sentence)
        category = map_hf_score_to_category(label_m1)

        category_counts[category] += 1

        results.append({"phrase": sentence, "score": score_m1, "category": category})

    # Identification des phrases contradictoires [cite: 1056]
    categories = [res['category'] for res in results]
    is_contradictory = (("Très Positif" in categories or "Positif" in categories) and
                        ("Très Négatif" in categories or "Négatif" in categories))

    distribution_total = len(sentences)
    distribution_percent = {k: v / distribution_total for k, v in category_counts.items()}

    return {
        "sentences": results,
        "is_contradictory": is_contradictory,
        "distribution_percent": distribution_percent
    }

def analyze_aspect_sentiment(text):
    """Tâche 1.3 & 2.2: Extraction et sentiment par aspect (Utilisation de spaCy pour le contexte) [cite: 1059]"""
    doc = nlp(text)
    aspect_sentiments = {}

    for aspect, keywords in ASPECTS_DICT.items():
        aspect_mentions_found = []

        # Trouver les phrases qui contiennent l'aspect (Tâche 2.2)
        for sent in doc.sents:
            for keyword in keywords:
                if re.search(r'\b' + re.escape(keyword) + r'\b', sent.text.lower()):
                    aspect_mentions_found.append(sent.text)
                    break

        if aspect_mentions_found:
            # Analyse du sentiment sur le contexte agrégé des mentions
            context = " ".join(aspect_mentions_found)
            score, _ = get_sentiment_score_hf(context)

            # Classification simple de l'aspect
            if score >= 0.2: category = "Positif"
            elif score <= -0.2: category = "Négatif"
            else: category = "Neutre"

            aspect_sentiments[aspect] = {
                "score": score,
                "category": category,
                "mentions_count": len(aspect_mentions_found)
            }

    return aspect_sentiments

def detect_emotions(text):
    """Tâche 2.3: Détection des 6 émotions principales et intensité. Utilise HF si disponible, sinon lexique."""

    if emotion_classifier:
        # Méthode 1: Hugging Face (plus précis)
        try:
            raw_emotions = emotion_classifier(text)[0]
            # Mapping spécifique pour le modèle roberta émotion
            EMOTION_MAP_HF = {
                "joy": "Joie / Satisfaction", "love": "Joie / Satisfaction",
                "anger": "Colère / Frustration", "sadness": "Tristesse / Déception",
                "fear": "Peur / Inquiétude", "surprise": "Surprise (positive/négative)"
            }

            processed_emotions = defaultdict(float)
            for item in raw_emotions:
                label = item['label'].lower()
                score = item['score']
                mapped_label = EMOTION_MAP_HF.get(label, None)
                if mapped_label:
                    processed_emotions[mapped_label] = max(processed_emotions[mapped_label], score)

        except Exception:
            # Fallback en cas de problème d'exécution
            processed_emotions = _detect_emotions_lexique(text)
    else:
        # Méthode 2: Lexique Custom (Tâche 2.3)
        processed_emotions = _detect_emotions_lexique(text)

    # Post-traitement et calcul de l'intensité
    if processed_emotions:
        max_intensity = max(processed_emotions.values())
    else:
        max_intensity = 0.0

    is_emotionally_charged = max_intensity > 0.7 # Seuil pour "chargé" [cite: 1085]

    return {
        "emotions": {k: v for k, v in processed_emotions.items() if v > 0.05},
        "max_intensity": max_intensity,
        "is_emotionally_charged": is_emotionally_charged
    }

def _detect_emotions_lexique(texte):
    """Fonction helper pour la détection d'émotions par lexique (Tâche 2.3)"""
    texte_lower = texte.lower()
    emotions_detectees = defaultdict(float)

    for emotion, mots_cles in EMOTIONS_LEXIQUE.items():
        compte = sum(1 for mot in mots_cles if re.search(r'\b' + re.escape(mot) + r'\b', texte_lower))
        if compte > 0:
            # Intensité normalisée (simplifiée)
            intensite = min(1.0, compte * 0.3)
            emotions_detectees[emotion] = intensite
    return emotions_detectees

# --- 3. Fonction Principale d'Exécution et de Collecte ---

class AnalyseurSentimentsComplet:
    """Regroupe l'exécution et la génération de rapports."""

    def __init__(self):
        self.resultats_globaux = []

    def analyser_avis_complet(self, avis, index):
        """Analyse complète d'un avis avec tous les niveaux et types"""

        doc_analysis = analyze_document_sentiment(avis)
        sent_analysis = split_and_analyze_sentences(avis)
        aspect_analysis = analyze_aspect_sentiment(avis)
        emotion_analysis = detect_emotions(avis)

        resultat_complet = {
            "avis_id": index + 1,
            "avis_text": avis,
            # Niveau Document & Polarité (T1.1, T2.1)
            "doc_score_m1_hf": doc_analysis['score_hf'],
            "doc_category": doc_analysis['category'],
            "polarite_vader": doc_analysis['score_vader'],
            "polarite_textblob": doc_analysis['score_textblob'],
            "coherence_multi_methodes": doc_analysis['coherence'],
            # Niveau Phrase (T1.2)
            "sentence_data": sent_analysis['sentences'],
            "is_contradictory": sent_analysis['is_contradictory'],
            "sent_distrib_percent": sent_analysis['distribution_percent'],
            # Niveau Aspect (T1.3, T2.2)
            "aspect_sentiments": aspect_analysis,
            # Détection d'Émotions (T2.3)
            "emotion_scores": emotion_analysis['emotions'],
            "max_emotion_intensity": emotion_analysis['max_intensity'],
            "is_emotionally_charged": emotion_analysis['is_emotionally_charged']
        }
        self.resultats_globaux.append(resultat_complet)
        return resultat_complet

    def analyser_tous_avis(self, avis_liste):
        """Analyse tous les avis et génère un résumé global"""
        self.resultats_globaux = []
        print("\n--- Démarrage de l'Analyse pour chaque Avis ---")
        for i, avis in enumerate(avis_liste):
            print(f"Analyse de l'Avis #{i+1}...")
            self.analyser_avis_complet(avis, i)

        self.generer_resume_global()
        self.generer_visualisations()
        self.exporter_resultats()

    # --- Fonctions de Reporting (Tâches Livrables) ---

    def generer_resume_global(self):
        """Génère un résumé statistique global (Tâche 1.1)"""
        print("\n" + "="*50)
        print("RÉSUMÉ GLOBAL DE L'ANALYSE (Statistiques et Recommandations)")
        print("="*50)

        if not self.resultats_globaux: return

        df_global = pd.DataFrame(self.resultats_globaux)

        # 1. Distribution globale des sentiments [cite: 1098]
        global_sentiment_distribution = df_global['doc_category'].value_counts(normalize=True).mul(100)
        print("\nDistribution Globale des Sentiments (Niveau Document):")
        print(global_sentiment_distribution.to_string(float_format="%.2f%%"))

        # 2. Aspect le plus critiqué/encensé [cite: 1065]
        all_aspects_scores = defaultdict(list)
        for r in self.resultats_globaux:
            for aspect, details in r['aspect_sentiments'].items():
                all_aspects_scores[aspect].append(details['score'])

        df_aspects_mean = pd.Series({k: np.mean(v) for k, v in all_aspects_scores.items()}).sort_values(ascending=False)

        if not df_aspects_mean.empty:
            aspect_critique = df_aspects_mean.index[-1]
            aspect_encense = df_aspects_mean.index[0]
            print(f"\n✨ Aspect le plus encensé: **{aspect_encense}** (Score: {df_aspects_mean.iloc[0]:.2f})")
            print(f"💀 Aspect le plus critiqué: **{aspect_critique}** (Score: {df_aspects_mean.iloc[-1]:.2f})")

        # 3. Émotion dominante [cite: 1142]
        all_emotion_scores = defaultdict(list)
        for r in self.resultats_globaux:
            for emotion, score in r['emotion_scores'].items():
                all_emotion_scores[emotion].append(score)

        if all_emotion_scores:
            df_emotions = pd.Series({k: np.mean(v) for k, v in all_emotion_scores.items()}).sort_values(ascending=False)
            print(f"\nÉmotion dominante: **{df_emotions.index[0]}** (Intensité moyenne: {df_emotions.iloc[0]:.2f})")

        print("\nRECOMMANDATIONS (Exemple):")
        print(f"- Améliorer la communication sur la valeur du produit pour justifier le **{aspect_critique.upper()}**.")

    def generer_visualisations(self):
        """Génère les visualisations demandées (Partie 2) [cite: 1097]"""
        if not self.resultats_globaux: return

        df_global = pd.DataFrame(self.resultats_globaux)

        plt.style.use('seaborn-v0_8-whitegrid')
        fig, axes = plt.subplots(2, 2, figsize=(15, 12))
        fig.suptitle('Tableau de Bord - Analyse de Sentiments', fontsize=18)

        # 1. Distribution globale des sentiments
        categories = df_global['doc_category'].value_counts().reindex(["Très Positif", "Positif", "Neutre", "Négatif", "Très Négatif"], fill_value=0)
        sns.barplot(x=categories.index, y=categories.values, palette="viridis", ax=axes[0, 0])
        axes[0, 0].set_title('Distribution Globale des Sentiments')
        axes[0, 0].set_ylabel('Nombre d\'avis')

        # 2. Comparaison des Méthodes de Polarité
        df_polarite = df_global[['doc_score_m1_hf', 'polarite_vader', 'polarite_textblob']].mean()
        df_polarite.index = ['HF BERT', 'VADER', 'TextBlob']
        sns.barplot(x=df_polarite.index, y=df_polarite.values, palette="Pastel1", ax=axes[0, 1])
        axes[0, 1].set_title('Score Moyen par Méthode de Polarité')
        axes[0, 1].axhline(0, color='gray', linestyle='--')

        # 3. Heatmap sentiments/aspects
        aspects_data = defaultdict(list)
        for r in self.resultats_globaux:
            for aspect in ASPECTS_DICT.keys():
                aspects_data[aspect].append(r['aspect_sentiments'].get(aspect, {}).get('score', 0))

        df_aspects = pd.DataFrame(aspects_data)
        df_aspects.index = [f"Avis {r['avis_id']}" for r in self.resultats_globaux]

        if not df_aspects.empty and len(df_aspects.columns) > 1:
            sns.heatmap(df_aspects.T, annot=True, fmt='.2f', cmap='RdYlGn', center=0, ax=axes[1, 0], cbar_kws={'label': 'Score de Sentiment'})
            axes[1, 0].set_title('Heatmap Sentiments par Aspect')

        # 4. Émotions dominantes
        all_emotion_scores = defaultdict(list)
        for r in self.resultats_globaux:
            for emotion, score in r['emotion_scores'].items():
                all_emotion_scores[emotion].append(score)

        if all_emotion_scores:
            df_emotions = pd.Series({k: np.mean(v) for k, v in all_emotion_scores.items()}).sort_values(ascending=False)
            sns.barplot(x=df_emotions.index, y=df_emotions.values, palette="tab10", ax=axes[1, 1])
            axes[1, 1].set_title('Intensité Émotionnelle Moyenne')
            axes[1, 1].set_ylabel('Intensité moyenne')
            axes[1, 1].tick_params(axis='x', rotation=45)

        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        plt.savefig('analyse_sentiments_dashboard.png', dpi=300)
        plt.show()

    def exporter_resultats(self):
        """Exporte les résultats en JSON et CSV (Partie 2) [cite: 1099]"""
        if not self.resultats_globaux: return

        # Export JSON complet
        with open('resultats_analyse_sentiments_complet.json', 'w', encoding='utf-8') as f:
            json.dump(self.resultats_globaux, f, ensure_ascii=False, indent=2)

        # Export CSV pour tableau de données
        data_csv = []
        for r in self.resultats_globaux:
            row = {
                'Avis_ID': r['avis_id'],
                'Texte': r['avis_text'][:100] + '...',
                'Cat_HF': r['doc_category'],
                'Score_HF': r['doc_score_m1_hf'],
                'Score_VADER': r['polarite_vader'],
                'Score_TextBlob': r['polarite_textblob'],
                'Cohérence_Multi': r['coherence_multi_methodes'],
                'Contradictions': r['is_contradictory'],
                'Charge_Emotionnelle': r['is_emotionally_charged']
            }
            # Ajouter les scores d'aspects
            for aspect in ASPECTS_DICT.keys():
                row[f'Aspect_{aspect}'] = r['aspect_sentiments'].get(aspect, {}).get('score', None)
            data_csv.append(row)

        df = pd.DataFrame(data_csv)
        df.to_csv('resultats_analyse_sentiments.csv', index=False, encoding='utf-8')

        print("\n--- Export des Livrables ---")
        print("Résultats exportés en CSV (resultats_analyse_sentiments.csv) et JSON.")

# --- 4. Tests Unitaires (Partie 1, Tâche 4 - OBLIGATOIRE) ---

class TestSentimentAnalysis(unittest.TestCase):
    """Tests unitaires pour les fonctions principales du script."""

    def test_a_document_analysis_polarity(self):
        """Teste l'analyse de polarité au niveau document (Méthode HF)."""
        # Avis clairement positif
        positive_avis = "C'est la meilleure expérience client que j'ai jamais eue, je suis très heureux!"
        analysis = analyze_document_sentiment(positive_avis)
        self.assertGreater(analysis['score_hf'], 0.5, "Le score HF doit être fortement Positif.")
        self.assertIn(analysis['category'], ["Très Positif", "Positif"], "La catégorie doit être Positif.")

        # Avis clairement négatif
        negative_avis = "Absolument terrible! La qualité est horrible et le support ne répond jamais."
        analysis = analyze_document_sentiment(negative_avis)
        self.assertLess(analysis['score_hf'], -0.5, "Le score HF doit être fortement Négatif.")
        self.assertIn(analysis['category'], ["Très Négatif"], "La catégorie doit être Très Négatif.")

    def test_b_sentence_analysis_contradiction(self):
        """Teste la détection de phrases contradictoires (Tâche 1.2)."""
        # Avis contradictoire (Utilisation de spaCy pour le split)
        contradictory_avis = "J'adore la performance du produit, c'est génial. Par contre, le prix est horriblement cher et la batterie est nulle."
        analysis = split_and_analyze_sentences(contradictory_avis)
        self.assertTrue(analysis['is_contradictory'], "La contradiction positive/négative doit être détectée.")
        self.assertEqual(len(analysis['sentences']), 2, "Doit détecter 2 phrases distinctes.")

    def test_c_aspect_analysis(self):
        """Teste l'analyse par aspect (Tâche 1.3) et la liaison aspect-sentiment."""
        avis = "Le service client était impeccable, un vrai plaisir. Mais la caméra est très mauvaise et la livraison fut lente."
        analysis = analyze_aspect_sentiment(avis)

        self.assertIn("Service", analysis, "L'aspect Service doit être trouvé.")
        self.assertIn("Livraison", analysis, "L'aspect Livraison doit être trouvé.")
        self.assertGreater(analysis.get("Service", {}).get("score", -1), 0.2, "Le score Service doit être positif.")
        self.assertLess(analysis.get("Livraison", {}).get("score", 1), -0.2, "Le score Livraison doit être négatif.")

    def test_d_emotion_detection(self):
        """Teste la détection d'émotions et la charge émotionnelle (Tâche 2.3)."""
        emotionnel = "Je suis tellement furieux de cette livraison endommagée! C'est une déception totale."
        analysis = detect_emotions(emotionnel)

        self.assertTrue(analysis['is_emotionally_charged'], "L'avis doit être émotionnellement chargé.")
        self.assertIn("Colère / Frustration", analysis['emotions'], "L'émotion de colère doit être détectée.")

# --- EXÉCUTION PRINCIPALE ---

if __name__ == "__main__":

    # 1. Exécution des tests unitaires
    print("="*70)
    print("--- Démarrage des TESTS UNITAIRES (Livrable Obligatoire) ---")
    print("="*70)
    loader = unittest.TestLoader()
    suite = loader.loadTestsFromTestCase(TestSentimentAnalysis)
    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)
    print("--- FIN des Tests Unitaires ---\n")

    # 2. Lancement de l'analyse complète
    analyseur = AnalyseurSentimentsComplet()
    analyseur.analyser_tous_avis(avis_clients)

    # 3. Affichage des résultats pour validation visuelle
    print("\n" + "="*70)
    print("=== AFFICHAGE DÉTAILLÉ DE L'EXEMPLE ATTENDU (Avis #1) ===")
    print("="*70)
    avis_1_result = next(r for r in analyseur.resultats_globaux if r['avis_id'] == 1)

    # Affichage formaté (similaire à l'exemple de sortie attendue) [cite: 1125]
    print(f"\nAvis #1:")
    print(f"  - Niveau Document: **{avis_1_result['doc_category']}** (score: {avis_1_result['doc_score_m1_hf']:.2f})")
    print(f"    (Cohérence Multi-Méthodes: {avis_1_result['coherence_multi_methodes']:.2f})")
    print("  - Niveau Phrase:")
    for i, sentence in enumerate(avis_1_result['sentence_data']):
        print(f"    * Phrase {i+1}: {sentence['category']} ({sentence['score']:.2f})")
    print("  - Niveau Aspect:")
    for aspect, data in avis_1_result['aspect_sentiments'].items():
        print(f"    * {aspect}: **{data['category']}** ({data['score']:.2f})")
    print("  - Émotions détectées:")
    for emotion, score in avis_1_result['emotion_scores'].items():
        print(f"    * {emotion}: (intensité: {score:.2f})")

    print("\n ANALYSE TERMINÉE AVEC SUCCÈS.")